config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :friends
  #get 'home/index'
  #each page need controller ie in terminal type [rails g controller home index]
  #to see all routes run [rails routes]
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index, show ]
  before_action :correct_user, only: %i[ edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    def correct_user
      @friend = current_user.friends.find_by(id: params[:id])
      redirect_to friends_path , notice: "Not authorized to edit this friend" if @friend.nil?
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :instagram, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
  
    def after_sign_up_path_for(resource)
        root_path #root_path is to diret user after sign in to root page
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name , class:"form-control", placeholder: 'First Name'%>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name , class:"form-control", placeholder: 'Last Name'%>
  </div>

  <div class="field form-group">
    <%= form.text_field :email , class:"form-control", placeholder: 'Email' %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone , class:"form-control" , placeholder: 'Phone Number' %>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter , class:"form-control" , placeholder: '@twitter'  %>
  </div>

  <div class="field form-group">
    <%= form.text_field :instagram , class:"form-control" , placeholder: '@instagram' %>
  </div>

 <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id,  class:"form-control" , value: current_user.id , type: :hidden%>
  </div>


  <div>
    <%= form.submit class: "btn btn-outline-dark"%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= friend.instagram %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>Instagram</th>
      <th>Profile</th>
      <th>User Id</th>
    </tr>
  </thead>


<h1>Friends List</h1>

<tbody>
  <% @friends.each do |friend| %>
  <tr>
      <td><%= friend.first_name %></td>
      <td><%= friend.last_name %></td>
      <td><%= friend.email %></td>
      <td><%= friend.phone %></td>
      <td><%= friend.twitter %></td>
      <td><%= friend.instagram %></td>
      <td><%= link_to friend.first_name+'_'+friend.last_name, friend %></td>
      <td><%= friend.user_id %> </td>
  </tr>
  <% end %>
</tbody>
</table>

<%= link_to "New friend", new_friend_path , class: "btn btn-outline-dark" %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<%= render "form", friend: @friend %>
<br>
<div>
  <%= link_to "Back to friends", friends_path , class: "btn btn-outline-dark"%>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %>
                        <%= @friend.last_name %></h1>

  <p class="lead">
                  <%= @friend.email %> |
                  <%= @friend.phone %> |
                  twitter: @<%= link_to @friend.twitter , 'https://twitter.com/'+@friend.twitter%> |
                  instagram: @<%= link_to @friend.instagram, 'https://www.instagram.com/'+@friend.instagram+'/'%>
  </p>
</div>


<div class="btn-group" role="group" aria-label="Basic example">
  <% if @friend.user != current_user %>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-outline-dark" %>
  <% else %>
  <%= link_to "Back to friends", friends_path , class: "btn btn-outline-dark" %>
  <%= button_to "Remove Friend", @friends, method: :delete , class: "btn btn-outline-dark" %>
  <% end %>
</div>
<br><br>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <%= link_to 'Friends List', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Friends', friends_path ,class:"nav-link" %>
        </li>
    
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-light" %>
        </li>    

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About us ...</h1>

app/views/home/index.html.erb
<h1>Welcome to Friends list 🚀🚀🚀🚀</h1>
<br>

<h2>

	Make an account at Sign Up and start adding friends and their Social media accounts!
</h2>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Friend List App</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    
    <div class="container">
      
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      
      <br/>
        <%= yield %>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>